### PR TITLE
Pet

### PR DESCRIPTION
**Pull request by valetronika**

### CODE REVIEW

**Review by AndreiBakhtinov — APPROVED** [review]
Good job!

**Review by yamyamiya — APPROVED** [review]
Nice!

**Review by sergey-zabolotnyi — APPROVED** [review]
Good job!

**Comment by uliana7sh** [comment]
goodJob!

**Review by IuliiaSadikova — APPROVED** [review]
Super!

**Review by AnnaDDD — APPROVED** [review]
+1

**Review by andretku — APPROVED** [review]

**Comment by SadurskisI** [comment]
All good

**Pull request merged**
